//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EG_MagicCubeEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Authors
    {
        public Authors()
        {
            this.AuthorsPropArea = new HashSet<AuthorsPropArea>();
            this.AuthorsPropTag = new HashSet<AuthorsPropTag>();
            this.WorksAuthors = new HashSet<WorksAuthors>();
        }
    
        public int AuthorsNo { get; set; }
        public string MaterialsID { get; set; }
        public string AuthorsCName { get; set; }
        public string AuthorsEName { get; set; }
        public string CreateUser { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string ModifyUser { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string Rating { get; set; }
        public int WorksAmount { get; set; }
        public string IsDel { get; set; }
    
        public virtual ICollection<AuthorsPropArea> AuthorsPropArea { get; set; }
        public virtual ICollection<AuthorsPropTag> AuthorsPropTag { get; set; }
        public virtual ICollection<WorksAuthors> WorksAuthors { get; set; }
    }
}
