//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EG_MagicCubeEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Authors
    {
        public Authors()
        {
            this.AuthorsPropArea = new HashSet<AuthorsPropArea>();
            this.AuthorsPropTag = new HashSet<AuthorsPropTag>();
            this.WorksAuthors = new HashSet<WorksAuthors>();
        }
    
        public int AuthorsNo { get; set; }
        public string MaterialsID { get; set; }
        public string AuthorsCName { get; set; }
        public string AuthorsEName { get; set; }
        public string CreateUser { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string ModifyUser { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    
        public virtual ICollection<AuthorsPropArea> AuthorsPropArea { get; set; }
        public virtual ICollection<AuthorsPropTag> AuthorsPropTag { get; set; }
        public virtual ICollection<WorksAuthors> WorksAuthors { get; set; }
    }
}
