//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EG_MagicCubeEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuthorsPropTag
    {
        public int AuthorsPropTagNo { get; set; }
        public int AuthorsNo { get; set; }
        public int AuthorsTagNo { get; set; }
    
        public virtual Authors Authors { get; set; }
        public virtual Menu_AuthorsTag Menu_AuthorsTag { get; set; }
    }
}
