//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EG_MagicCubeEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu_AuthorsTag
    {
        public Menu_AuthorsTag()
        {
            this.AuthorsPropTag = new HashSet<AuthorsPropTag>();
        }
    
        public int AuthorsTagNo { get; set; }
        public string AuthorsTagName { get; set; }
    
        public virtual ICollection<AuthorsPropTag> AuthorsPropTag { get; set; }
    }
}
