//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EG_MagicCubeEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu_AuthorsArea
    {
        public Menu_AuthorsArea()
        {
            this.AuthorsPropArea = new HashSet<AuthorsPropArea>();
        }
    
        public int AuthorsAreaNo { get; set; }
        public string AuthorsAreaName { get; set; }
    
        public virtual ICollection<AuthorsPropArea> AuthorsPropArea { get; set; }
    }
}
