//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EG_MagicCubeEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu_Genre
    {
        public Menu_Genre()
        {
            this.WorksPropGenre = new HashSet<WorksPropGenre>();
        }
    
        public int GenreNo { get; set; }
        public string GenreName { get; set; }
        public string IsDel { get; set; }
    
        public virtual ICollection<WorksPropGenre> WorksPropGenre { get; set; }
    }
}
