//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EG_MagicCubeEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu_Material
    {
        public Menu_Material()
        {
            this.WorksModules = new HashSet<WorksModules>();
        }
    
        public int MaterialNo { get; set; }
        public string MaterialName { get; set; }
    
        public virtual ICollection<WorksModules> WorksModules { get; set; }
    }
}
