//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EG_MagicCubeEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Packages
    {
        public Packages()
        {
            this.PackageItems = new HashSet<PackageItems>();
        }
    
        public System.Guid PackagesNo { get; set; }
        public string PackagesName { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> PackingDate { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateUser { get; set; }
        public string ModifyUser { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string SearchJson { get; set; }
        public string PackagesMemo { get; set; }
    
        public virtual ICollection<PackageItems> PackageItems { get; set; }
    }
}
