//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EG_MagicCubeEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackageItems
    {
        public long PackageItemsNo { get; set; }
        public System.Guid PackagesNo { get; set; }
        public System.Guid WorksNo { get; set; }
        public System.DateTime JoinDate { get; set; }
        public Nullable<System.DateTime> DelDate { get; set; }
        public string IsJoin { get; set; }
    
        public virtual Packages Packages { get; set; }
        public virtual Works Works { get; set; }
    }
}
