//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EG_MagicCubeEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Packages
    {
        public Packages()
        {
            this.PackageItems = new HashSet<PackageItems>();
        }
    
        public System.Guid PackagesNo { get; set; }
        public string PackagesName { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> PackingDate { get; set; }
        public string SearchJson { get; set; }
        public string PackagesMemo { get; set; }
        public string CreateUser { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string ModifyUser { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public int Budget { get; set; }
        public string IsDel { get; set; }
    
        public virtual ICollection<PackageItems> PackageItems { get; set; }
    }
}
