//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EG_MagicCubeEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccounts
    {
        public int UserAccountsNo { get; set; }
        public string Password { get; set; }
        public string Pwdself { get; set; }
        public string Name { get; set; }
        public int RoleNo { get; set; }
        public string AccountStatus { get; set; }
        public string AccountNote { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateUser { get; set; }
        public string ModifyUser { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string UserAccount { get; set; }
    
        public virtual UserAccountRoles UserAccountRoles { get; set; }
    }
}
