//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EG_MagicCubeEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccountRoles
    {
        public UserAccountRoles()
        {
            this.UserAccounts = new HashSet<UserAccounts>();
        }
    
        public int RoleNo { get; set; }
        public string RoleName { get; set; }
    
        public virtual ICollection<UserAccounts> UserAccounts { get; set; }
    }
}
