//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EG_MagicCubeEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorksModules
    {
        public int WorksModulesNo { get; set; }
        public System.Guid WorksNo { get; set; }
        public int Material { get; set; }
        public string Measure { get; set; }
        public double Length { get; set; }
        public double Width { get; set; }
        public double Height { get; set; }
        public double Deep { get; set; }
        public string TimeLength { get; set; }
        public int Amount { get; set; }
        public int CountNoun { get; set; }
    
        public virtual Menu_CountNoun Menu_CountNoun { get; set; }
        public virtual Menu_Material Menu_Material { get; set; }
        public virtual Works Works { get; set; }
    }
}
