//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EG_MagicCubeEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Works
    {
        public Works()
        {
            this.PackageItems = new HashSet<PackageItems>();
            this.WorksAuthors = new HashSet<WorksAuthors>();
            this.WorksFiles = new HashSet<WorksFiles>();
            this.WorksModules = new HashSet<WorksModules>();
            this.WorksPropGenre = new HashSet<WorksPropGenre>();
            this.WorksPropOwner = new HashSet<WorksPropOwner>();
            this.WorksPropStyle = new HashSet<WorksPropStyle>();
            this.WorksPropWareType = new HashSet<WorksPropWareType>();
        }
    
        public System.Guid WorksNo { get; set; }
        public string MaterialsID { get; set; }
        public int AuthorsNo { get; set; }
        public string WorksName { get; set; }
        public short YearStart { get; set; }
        public short YearEnd { get; set; }
        public string Remarks { get; set; }
        public int Cost { get; set; }
        public Nullable<System.DateTime> PricingDate { get; set; }
        public double GrossMargin { get; set; }
        public double Marketability { get; set; }
        public double Packageability { get; set; }
        public double Valuability { get; set; }
        public double Artisticability { get; set; }
        public string CreateUser { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string ModifyUser { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string Rating { get; set; }
        public string IsDel { get; set; }
        public int Purchase { get; set; }
        public string Material { get; set; }
        public string MaterialEng { get; set; }
        public string Currency { get; set; }
        public string ZFVOLUME { get; set; }
        public string ZZPAGE { get; set; }
        public string WorkSize { get; set; }
        public string GenreName { get; set; }
        public int TotalInventory { get; set; }
        public string ChangeState { get; set; }
    
        public virtual ICollection<PackageItems> PackageItems { get; set; }
        public virtual ICollection<WorksAuthors> WorksAuthors { get; set; }
        public virtual ICollection<WorksFiles> WorksFiles { get; set; }
        public virtual ICollection<WorksModules> WorksModules { get; set; }
        public virtual ICollection<WorksPropGenre> WorksPropGenre { get; set; }
        public virtual ICollection<WorksPropOwner> WorksPropOwner { get; set; }
        public virtual ICollection<WorksPropStyle> WorksPropStyle { get; set; }
        public virtual ICollection<WorksPropWareType> WorksPropWareType { get; set; }
    }
}
