//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EG_MagicCubeEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorksPropOwner
    {
        public int WorksPropOwnerNo { get; set; }
        public System.Guid WorksNo { get; set; }
        public int OwnerNo { get; set; }
    
        public virtual Menu_Owner Menu_Owner { get; set; }
        public virtual Works Works { get; set; }
    }
}
