//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EG_MagicCubeEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorksFiles
    {
        public long WorksFilesNo { get; set; }
        public System.Guid WorksNo { get; set; }
        public string FileBase64Str { get; set; }
        public string File_o_Url { get; set; }
        public string File_m_Url { get; set; }
        public string File_s_Url { get; set; }
        public short Sorting { get; set; }
    
        public virtual Works Works { get; set; }
    }
}
