//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EG_MagicCube.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu_CountNoun
    {
        public Menu_CountNoun()
        {
            this.Works_Module_List = new HashSet<Works_Module_List>();
        }
    
        public int CountNoun_No { get; set; }
        public string CountNoun_Name { get; set; }
    
        public virtual ICollection<Works_Module_List> Works_Module_List { get; set; }
    }
}
