//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EG_MagicCube.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Author_Prop_Area
    {
        public int AuthorPropArea_No { get; set; }
        public int Author_No { get; set; }
        public int AuthorArea_No { get; set; }
    
        public virtual Author_List Author_List { get; set; }
        public virtual Menu_AuthorArea Menu_AuthorArea { get; set; }
    }
}
