//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EG_MagicCube.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Author_List
    {
        public Author_List()
        {
            this.Author_Prop_Area = new HashSet<Author_Prop_Area>();
            this.Author_Prop_Tag = new HashSet<Author_Prop_Tag>();
            this.Works_Author = new HashSet<Works_Author>();
        }
    
        public int Author_No { get; set; }
        public string Materials_ID { get; set; }
        public string AuthorCName { get; set; }
        public string AuthorEName { get; set; }
        public string CreateUser { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string ModifyUser { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    
        public virtual ICollection<Author_Prop_Area> Author_Prop_Area { get; set; }
        public virtual ICollection<Author_Prop_Tag> Author_Prop_Tag { get; set; }
        public virtual ICollection<Works_Author> Works_Author { get; set; }
    }
}
