//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EG_MagicCube.Models.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EG_MagicCubeEntities : DbContext
    {
        public EG_MagicCubeEntities()
            : base("name=EG_MagicCubeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Author_List> Author_List { get; set; }
        public DbSet<Author_Prop_Area> Author_Prop_Area { get; set; }
        public DbSet<Author_Prop_Tag> Author_Prop_Tag { get; set; }
        public DbSet<Menu_AuthorArea> Menu_AuthorArea { get; set; }
        public DbSet<Menu_AuthorTag> Menu_AuthorTag { get; set; }
        public DbSet<Menu_CountNoun> Menu_CountNoun { get; set; }
        public DbSet<Menu_Genre> Menu_Genre { get; set; }
        public DbSet<Menu_Material> Menu_Material { get; set; }
        public DbSet<Menu_Owner> Menu_Owner { get; set; }
        public DbSet<Menu_Style> Menu_Style { get; set; }
        public DbSet<Menu_WareType> Menu_WareType { get; set; }
        public DbSet<Package_List> Package_List { get; set; }
        public DbSet<PackageItemList> PackageItemList { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<User_AccountList> User_AccountList { get; set; }
        public DbSet<Works_Author> Works_Author { get; set; }
        public DbSet<Works_List> Works_List { get; set; }
        public DbSet<Works_Module_List> Works_Module_List { get; set; }
        public DbSet<Works_Prop_Genre> Works_Prop_Genre { get; set; }
        public DbSet<Works_Prop_Owner> Works_Prop_Owner { get; set; }
        public DbSet<Works_Prop_Style> Works_Prop_Style { get; set; }
        public DbSet<Works_Prop_WareType> Works_Prop_WareType { get; set; }
    }
}
