//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EG_MagicCube.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu_Style
    {
        public Menu_Style()
        {
            this.Works_Prop_Style = new HashSet<Works_Prop_Style>();
        }
    
        public int Style_No { get; set; }
        public string Style_Name { get; set; }
    
        public virtual ICollection<Works_Prop_Style> Works_Prop_Style { get; set; }
    }
}
