//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EG_MagicCube.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu_CountNoun
    {
        public Menu_CountNoun()
        {
            this.Works_Module_List = new HashSet<Works_Module_List>();
        }
    
        public int CountNoun_No { get; set; }
        public string CountNoun_Name { get; set; }
    
        public virtual ICollection<Works_Module_List> Works_Module_List { get; set; }
    }
}
