//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EG_MagicCube.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu_WareType
    {
        public Menu_WareType()
        {
            this.Works_Prop_WareType = new HashSet<Works_Prop_WareType>();
        }
    
        public int WareType_No { get; set; }
        public string WareType_Name { get; set; }
    
        public virtual ICollection<Works_Prop_WareType> Works_Prop_WareType { get; set; }
    }
}
