//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EG_MagicCube.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu_AuthorArea
    {
        public Menu_AuthorArea()
        {
            this.Author_Prop_Area = new HashSet<Author_Prop_Area>();
        }
    
        public int AuthorArea_No { get; set; }
        public string AuthorArea_Name { get; set; }
    
        public virtual ICollection<Author_Prop_Area> Author_Prop_Area { get; set; }
    }
}
