//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EG_MagicCube.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu_Owner
    {
        public Menu_Owner()
        {
            this.Works_Prop_Owner = new HashSet<Works_Prop_Owner>();
        }
    
        public int Owner_No { get; set; }
        public string Owner_Name { get; set; }
    
        public virtual ICollection<Works_Prop_Owner> Works_Prop_Owner { get; set; }
    }
}
