//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EG_MagicCube.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu_Genre
    {
        public Menu_Genre()
        {
            this.Works_Prop_Genre = new HashSet<Works_Prop_Genre>();
        }
    
        public int Genre_No { get; set; }
        public string Genre_Name { get; set; }
    
        public virtual ICollection<Works_Prop_Genre> Works_Prop_Genre { get; set; }
    }
}
