//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EG_MagicCube.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu_AuthorTag
    {
        public Menu_AuthorTag()
        {
            this.Author_Prop_Tag = new HashSet<Author_Prop_Tag>();
        }
    
        public int AuthorTag_No { get; set; }
        public string AuthorTag_Name { get; set; }
    
        public virtual ICollection<Author_Prop_Tag> Author_Prop_Tag { get; set; }
    }
}
