//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EG_MagicCube.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Package_List
    {
        public Package_List()
        {
            this.PackageItemList = new HashSet<PackageItemList>();
        }
    
        public System.Guid PG_No { get; set; }
        public string PG_Name { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> PackingDate { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateUser { get; set; }
        public string ModifyUser { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    
        public virtual ICollection<PackageItemList> PackageItemList { get; set; }
    }
}
