//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EG_MagicCube.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackageItemList
    {
        public long PGItem_No { get; set; }
        public System.Guid PG_No { get; set; }
        public System.Guid Works_No { get; set; }
        public System.DateTime JoinDate { get; set; }
        public Nullable<System.DateTime> DelDate { get; set; }
    
        public virtual Package_List Package_List { get; set; }
        public virtual Works_List Works_List { get; set; }
    }
}
