//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EG_MagicCube.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_AccountList
    {
        public int Account_No { get; set; }
        public string Password { get; set; }
        public string Pwdself { get; set; }
        public string Name { get; set; }
        public string Account_Role { get; set; }
        public string Account_Status { get; set; }
        public string Account_Note { get; set; }
    }
}
