//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EG_MagicCube.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Works_Module_List
    {
        public int Works_Module_No { get; set; }
        public System.Guid Works_No { get; set; }
        public int Material { get; set; }
        public string Measure { get; set; }
        public double Length { get; set; }
        public double Width { get; set; }
        public double High { get; set; }
        public double Deep { get; set; }
        public string TimeLength { get; set; }
        public int Amount { get; set; }
        public int CountNoun { get; set; }
    
        public virtual Menu_CountNoun Menu_CountNoun { get; set; }
        public virtual Menu_Material Menu_Material { get; set; }
        public virtual Works_List Works_List { get; set; }
    }
}
