//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EG_MagicCube.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Works_Author
    {
        public int Works_Author_No { get; set; }
        public System.Guid Works_No { get; set; }
        public int Author_No { get; set; }
    
        public virtual Author_List Author_List { get; set; }
        public virtual Works_List Works_List { get; set; }
    }
}
