//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EG_MagicCube.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Works_List
    {
        public Works_List()
        {
            this.PackageItemList = new HashSet<PackageItemList>();
            this.Works_Author = new HashSet<Works_Author>();
            this.Works_Module_List = new HashSet<Works_Module_List>();
            this.Works_Prop_Genre = new HashSet<Works_Prop_Genre>();
            this.Works_Prop_Owner = new HashSet<Works_Prop_Owner>();
            this.Works_Prop_Style = new HashSet<Works_Prop_Style>();
            this.Works_Prop_WareType = new HashSet<Works_Prop_WareType>();
        }
    
        public System.Guid Works_No { get; set; }
        public string Materials_ID { get; set; }
        public int Author_No { get; set; }
        public string WorksName { get; set; }
        public short Year_Start { get; set; }
        public short Year_End { get; set; }
        public string Remarks { get; set; }
        public int Cost { get; set; }
        public int Price { get; set; }
        public System.DateTime PricingDate { get; set; }
        public double GrossMargin { get; set; }
        public double Marketability { get; set; }
        public double Packageability { get; set; }
        public double Valuability { get; set; }
        public double Artisticability { get; set; }
        public string CreateUser { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string ModifyUser { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    
        public virtual ICollection<PackageItemList> PackageItemList { get; set; }
        public virtual ICollection<Works_Author> Works_Author { get; set; }
        public virtual ICollection<Works_Module_List> Works_Module_List { get; set; }
        public virtual ICollection<Works_Prop_Genre> Works_Prop_Genre { get; set; }
        public virtual ICollection<Works_Prop_Owner> Works_Prop_Owner { get; set; }
        public virtual ICollection<Works_Prop_Style> Works_Prop_Style { get; set; }
        public virtual ICollection<Works_Prop_WareType> Works_Prop_WareType { get; set; }
    }
}
